-- MySQL Script generated by MySQL Workbench
-- Sat Oct 23 22:01:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `role` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `auteur` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `titre` VARCHAR(45) NOT NULL,
  `contenu` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Categorie_idCategorie` INT NOT NULL,
  PRIMARY KEY (`idPost`, `Utilisateur_idUtilisateur`, `Categorie_idCategorie`),
  INDEX `fk_Post_Utilisateur_idx` (`Utilisateur_idUtilisateur` ASC) ,
  INDEX `fk_Post_Catégorie1_idx` (`Categorie_idCategorie` ASC) ,
  CONSTRAINT `fk_Post_Utilisateur`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Categorie1`
    FOREIGN KEY (`Categorie_idCategorie`)
    REFERENCES `mydb`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commentaire` (
  `idCommentaire` INT NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Post_idPost` INT NOT NULL,
  `Post_Utilisateur_idUtilisateur` INT NOT NULL,
  `Post_Categorie_idCategorie` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idCommentaire`, `Post_idPost`, `Post_Utilisateur_idUtilisateur`, `Post_Categorie_idCategorie`, `Utilisateur_idUtilisateur`),
  INDEX `fk_Commentaire_Post1_idx` (`Post_idPost` ASC, `Post_Utilisateur_idUtilisateur` ASC, `Post_Categorie_idCategorie` ASC) ,
  INDEX `fk_Commentaire_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC) ,
  CONSTRAINT `fk_Commentaire_Post1`
    FOREIGN KEY (`Post_idPost` , `Post_Utilisateur_idUtilisateur` , `Post_Categorie_idCategorie`)
    REFERENCES `mydb`.`Post` (`idPost` , `Utilisateur_idUtilisateur` , `Categorie_idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

